### ISSUE TITLE
Rosalba Client is not an open-source client

### ISSUE THREAD

**Issue by liujiang71352** [ImCzf233/FakeBounce-Killer#29]
They point out in the readme.txt and QQ group
They have added obfuscation to the client, which is used to prevent clients from anti-obfuscating the client
File Link:https://www.mediafire.com/file/646fjhmtytdu4dg/Rosalba+B2.0.jar/file
https://lanzout.com/ivjTy068pmmj
The Evidence:

> 请勿倒卖 解密(Do Not Sell or Decrypt)
> 使用请加群XXXXXXXXXX(To use, please join the group)
> 水影不开源 再问kick(No open source, if you ask again you will be kicked out)

**Comment by nuym** [comment]
十分支持此项目！
