### ISSUE TITLE
I don't know if it's just me or something but "Celestial client" seems to be made of liquidbounce.

### ISSUE THREAD

**Issue by zEncrypte** [ImCzf233/FakeBounce-Killer#7]

**Comment by SkiderKiller** [comment]
You should provide us with the jar file of the cellular client.

**Comment by zEncrypte** [comment]
the client is a pay client but I saw a live on discord

**Comment by XSilverTH** [comment]
its not a liquidbounce fork its a full client and i have a crack of it but i dont use it (i dont like using cracks but liquid doesnt allow closed source forks so ig its fine lmao)
